# Generated by Django 5.0.4 on 2024-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
