# Generated by Django 5.0.4 on 2024-04-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
