# Generated by Django 5.0.4 on 2024-04-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_remove_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
