# Generated by Django 5.0.4 on 2024-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_username_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='Faces/')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
