# Generated by Django 5.0.4 on 2024-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_newuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HID', models.CharField(max_length=6)),
                ('stuid', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('cardnum', models.CharField(max_length=9)),
            ],
        ),
    ]
